// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbsQUNHv5u-3km3UMmQ8l2UP4bLI0K10',
    appId: '1:1004140766224:android:17b75e34d5d9d00c299695',
    messagingSenderId: '1004140766224',
    projectId: 'softwarelabsassignment',
    databaseURL: 'https://softwarelabsassignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'softwarelabsassignment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGe7SFsH8Nq-brL_H1g8gtjrWg7vnLq_4',
    appId: '1:1004140766224:ios:3bca87b75ddac52d299695',
    messagingSenderId: '1004140766224',
    projectId: 'softwarelabsassignment',
    databaseURL: 'https://softwarelabsassignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'softwarelabsassignment.firebasestorage.app',
    androidClientId: '1004140766224-4hp46u93590p7c5eq3l74q18gdmrdtcr.apps.googleusercontent.com',
    iosClientId: '1004140766224-8iqev8eugb2tt4nhijdda61e17tm59c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.softwarelabsIos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGe7SFsH8Nq-brL_H1g8gtjrWg7vnLq_4',
    appId: '1:1004140766224:ios:3bca87b75ddac52d299695',
    messagingSenderId: '1004140766224',
    projectId: 'softwarelabsassignment',
    databaseURL: 'https://softwarelabsassignment-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'softwarelabsassignment.firebasestorage.app',
    androidClientId: '1004140766224-4hp46u93590p7c5eq3l74q18gdmrdtcr.apps.googleusercontent.com',
    iosClientId: '1004140766224-8iqev8eugb2tt4nhijdda61e17tm59c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.softwarelabsIos',
  );

}